import card_util as gu

def main():
      print()
      print("-" * 60)
      print(" " * 20 + " create_full_deck() " + " " * 20)
      print(" " * 20 + " print_deck(deck) " + " " * 20)
      print("-" * 60)
      print()
      deck = gu.create_std_deck()
      gu.print_deck(deck) 

      print()
      print("-" * 60)
      print(" " * 20 + " shuffle_cards(deck) " + " " * 20)
      print(" " * 20 + " print_deck(deck) " + " " * 20)
      print("-" * 60)
      print()
      gu.shuffle_cards(deck)
      gu.print_deck(deck)

      print()
      print("-" * 20 + " Shuffling the deck again " + "-" * 20)
      print()
      gu.shuffle_cards(deck)
      gu.print_deck(deck)

      print()
      print("-" * 60)
      print(" " * 20 + " deal_cards_from(deck, 10) " + " " * 20)
      print(" " * 20 + " print_deck(p1_deck) " + " " * 20)
      print("-" * 60)
      print()
      print("Player 1 Deck:")
      p1_deck = gu.deal_cards_from(deck, 10)
      gu.print_deck(p1_deck)
      print("Player 1 Deck size:", len(p1_deck))
      print()
      print("Original Deck:")
      gu.print_deck(deck)
      print("Original Deck size:", len(deck))
      print()

      print()
      print("-" * 60)
      print(" " * 20 + " deal_cards_from(deck, 10) " + " " * 20)
      print(" " * 20 + " print_deck(p2_deck) " + " " * 20)
      print("-" * 60)
      print()
      print("Player 2 Deck:")
      p2_deck = gu.deal_cards_from(deck, 10)
      gu.print_deck(p2_deck)
      print("Player 2 Deck size:", len(p2_deck))
      print()
      print("Player 1 Deck:")
      gu.print_deck(p1_deck)
      print("Player 1 Deck size:", len(p1_deck))
      print()
      print("Original Deck:")
      gu.print_deck(deck)
      print("Original Deck size:", len(deck))
      print()


      print()
      print("-" * 60)
      print(" " * 20 + " deal_cards_from(p1_deck, 3) " + " " * 20)
      print(" " * 20 + " deal_cards_from(p2_deck, 5) " + " " * 20)
      print(" " * 20 + " add_cards_to(p1_deck, p1_play) " + " " * 20)
      print(" " * 20 + " add_cards_to(p1_deck, p2_play) " + " " * 20)
      print("-" * 60)
      print()
      p1_play = gu.deal_cards_from(p1_deck, 3)
      p2_play = gu.deal_cards_from(p2_deck, 5)

      print("Player 1 plays cards:", end = " ")
      gu.print_deck(p1_play)
      print()

      print("Player 2 plays cards:", end = " ")
      gu.print_deck(p2_play)
      print() 

      print("Player 1 wins all cards.")
      gu.add_cards_to(p1_deck, p1_play)
      gu.add_cards_to(p1_deck, p2_play)


      print()
      print("Player 1 Deck:")
      gu.print_deck(p1_deck)
      print("Player 1 Deck size:", len(p1_deck))
      print()
      print("Player 2 Deck:")
      gu.print_deck(p2_deck)
      print("Player 1 Deck size:", len(p2_deck))
      print()

      print("Original Deck:")
      gu.print_deck(deck)
      print("Original Deck size:", len(deck))
      print()

      print()
      print("-" * 60)
      print(" " * 20 + " print_deck(p1_deck) " + " " * 20)
      print(" " * 20 + " print_deck(p2_deck) " + " " * 20)
      print(" " * 20 + " print_deck(deck, False) " + " " * 20)
      print("-" * 60)
      print()



      print()
      print("Player 1 Deck:")
      gu.print_deck(p1_deck)
      print("Player 1 Deck size:", len(p1_deck))
      print()
      print("Player 2 Deck:")
      gu.print_deck(p2_deck)
      print("Player 1 Deck size:", len(p2_deck))
      print()

      print("Original Deck:")
      gu.print_deck(deck, False)
      print("Original Deck size:", len(deck))
      print()