from card import Card

def main():
  card1 = Card(1, 'HEARTS')
  card1.print_card()
  print("String:", card1)
  print("Rank:", card1.get_rank())
  print("Suit:", card1.get_suit())
  card2 = Card(10, 'SPADES')
  card2.print_card()
  print("String:", card2)
  print("Rank:", card2.get_rank())
  print("Suit:", card2.get_suit())
  print()
  card3 = Card(11, 'CLUBS')
  card3.print_card()
  print("String:", card3)
  print("Rank:", card3.get_rank())
  print("Suit:", card3.get_suit())
  print()
  card4 = Card(12, 'DIAMONDS')
  card4.print_card()
  print("String:", card4)
  print("Rank:", card4.get_rank())
  print("Suit:", card4.get_suit())
  print()
  card5 = Card(13, 'HEARTS')
  card5.print_card()
  print("String:", card5)
  print("Rank:", card5.get_rank())
  print("Suit:", card5.get_suit())
  print()
  card6 = Card(2, 'SPADES')
  card6.print_card()
  print("String:", card6)
  print("Rank:", card6.get_rank())
  print("Suit:", card6.get_suit())
  print()
  